version: '3.7'

services:
  nginx:
    image: openresty/openresty:latest
    container_name: edeka-or
    ports: 
      - 127.0.0.1:8080:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      driver: 'json-file'
      options:
        max-size: "200k"
        max-file: "5"

  mock-service:
    build: .
    container_name: edeka-or-backend
    volumes:
      - type: bind
        source: ./www
        target: /www
    logging:
      driver: 'json-file'
      options:
        max-size: "200k"
        max-file: "5"
